// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalI5P2d861k1GDRPJUxyQc-34pnGpvfQ',
    appId: '1:820472487227:web:5e10985c4abe50cb216b1e',
    messagingSenderId: '820472487227',
    projectId: 'wovell-1ea6e',
    authDomain: 'wovell-1ea6e.firebaseapp.com',
    storageBucket: 'wovell-1ea6e.firebasestorage.app',
    measurementId: 'G-5HBPFKHV63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiNDJfbFYx-_2cqmgfRILnZ38FBUYpRs',
    appId: '1:820472487227:android:3f69d9c624276af3216b1e',
    messagingSenderId: '820472487227',
    projectId: 'wovell-1ea6e',
    storageBucket: 'wovell-1ea6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYzczbMKsLL-pT_5KAryrlNY8cGNrAudU',
    appId: '1:820472487227:ios:766cbce1695d96df216b1e',
    messagingSenderId: '820472487227',
    projectId: 'wovell-1ea6e',
    storageBucket: 'wovell-1ea6e.firebasestorage.app',
    iosBundleId: 'com.example.wovellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYzczbMKsLL-pT_5KAryrlNY8cGNrAudU',
    appId: '1:820472487227:ios:766cbce1695d96df216b1e',
    messagingSenderId: '820472487227',
    projectId: 'wovell-1ea6e',
    storageBucket: 'wovell-1ea6e.firebasestorage.app',
    iosBundleId: 'com.example.wovellApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalI5P2d861k1GDRPJUxyQc-34pnGpvfQ',
    appId: '1:820472487227:web:575094f3086c47c0216b1e',
    messagingSenderId: '820472487227',
    projectId: 'wovell-1ea6e',
    authDomain: 'wovell-1ea6e.firebaseapp.com',
    storageBucket: 'wovell-1ea6e.firebasestorage.app',
    measurementId: 'G-42BJ6JSPVX',
  );
}
